<a href="https://colab.research.google.com/github/endah-nurfebriyanti/data-cleaning-with-pandas/blob/main/Data_Clean_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("Harvard_English_Centre_Payments_2025_Dirty.csv")

In [ ]:
df.head()

,Payment_ID,Payment_Date,Month,Student_ID,Subject,Level,Tutor,Payment_Method,Course_Fee,Discount,Amount_Paid,Payment_Status,Student_Status
0,PAY01001,2025-11-24,November,STU0115,IELTS,Advanced,Sarah,Cash,500000,NaN,NaN,paid,Active
1,PAY01002,2025/10/30,October,STU0120,English,Advanced,Linda,Cash,500000,0.0,500000.0,paid,Actve
2,PAY01003,2025/04/23,April,STU0004,IELTS,Advanced,Jhon,Bank Transfer,5000000,50000.0,4950000.0,Unpaid,Inactive
3,PAY01004,"Apr 21, 2025",April,STU0184,Grammar,Advanced,David,NaN,500000,0.0,500000.0,Paid,Actve
4,PAY01005,2025-10-02,October,STU0425,Grammar,Advanced,Linda,Cash,750000,0.0,750000.0,Paid,Active

In [ ]:
df.shape

(2020, 13)

In [ ]:
df.columns

Index(['Payment_ID', 'Payment_Date', 'Month', 'Student_ID', 'Subject', 'Level',
       'Tutor', 'Payment_Method', 'Course_Fee', 'Discount', 'Amount_Paid',
       'Payment_Status', 'Student_Status'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Payment_ID      2020 non-null   object
 1   Payment_Date    2020 non-null   object
 2   Month           2020 non-null   object
 3   Student_ID      2020 non-null   object
 4   Subject         2020 non-null   object
 5   Level           2020 non-null   object
 6   Tutor           1824 non-null   object
 7   Payment_Method  1745 non-null   object
 8   Course_Fee      2020 non-null   int64
 9   Discount        1676 non-null   float64
 10  Amount_Paid     1676 non-null   float64
 11  Payment_Status  2020 non-null   object
 12  Student_Status  2020 non-null   object
dtypes: float64(2), int64(1), object(10)
memory usage: 205.3+ KB

In [ ]:
df.describe()

         Course_Fee       Discount   Amount_Paid
count  2.020000e+03    1676.000000  1.676000e+03
mean   1.451955e+06   27088.305489  1.358473e+06
std    1.691025e+06   49317.375648  1.702725e+06
min    5.000000e+05  -50000.000000 -5.050000e+06
25%    6.500000e+05       0.000000  5.500000e+05
50%    7.000000e+05   25000.000000  6.500000e+05
75%    7.500000e+05   50000.000000  7.500000e+05
max    5.000000e+06  100000.000000  5.050000e+06

In [ ]:
df.duplicated().sum()

np.int64(20)

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.isnull().sum()

Payment_ID        0
Payment_Date      0
Month             0
Student_ID        0
Subject           0
Level             0
Tutor             0
Payment_Method    0
Course_Fee        0
Discount          0
Amount_Paid       0
Payment_Status    0
Student_Status    0
dtype: int64

In [ ]:
df["Tutor"]=df["Tutor"].fillna("Unknown")

In [ ]:
df["Discount"]=df["Discount"].fillna(0)

In [ ]:
df["Amount_Paid"]=df["Amount_Paid"].fillna(df["Course_Fee"]-df["Discount"])

In [ ]:
df.isnull().sum()

Payment_ID          0
Payment_Date        0
Month               0
Student_ID          0
Subject             0
Level               0
Tutor               0
Payment_Method    273
Course_Fee          0
Discount            0
Amount_Paid         0
Payment_Status      0
Student_Status      0
dtype: int64

In [ ]:
df["Payment_Method"]=df["Payment_Method"].fillna("Unknown")

In [ ]:
df.isnull().sum()

Payment_ID        0
Payment_Date      0
Month             0
Student_ID        0
Subject           0
Level             0
Tutor             0
Payment_Method    0
Course_Fee        0
Discount          0
Amount_Paid       0
Payment_Status    0
Student_Status    0
dtype: int64

In [ ]:
df["Payment_Date"]=pd.to_datetime(df["Payment_Date"],format="mixed",dayfirst=True)

In [ ]:
df["Year"]=df["Payment_Date"].dt.year

In [ ]:
df["Quarter"]=df["Payment_Date"].dt.quarter

In [ ]:
df["Month_Name"]=df["Payment_Date"].dt.month_name()

In [ ]:
df["Week"]=df["Payment_Date"].dt.isocalendar().week

In [ ]:
df["Day"]=df["Payment_Date"].dt.day_name()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 0 to 1999
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Payment_ID      2000 non-null   object
 1   Payment_Date    2000 non-null   datetime64[ns]
 2   Month           2000 non-null   object
 3   Student_ID      2000 non-null   object
 4   Subject         2000 non-null   object
 5   Level           2000 non-null   object
 6   Tutor           2000 non-null   object
 7   Payment_Method  2000 non-null   object
 8   Course_Fee      2000 non-null   int64
 9   Discount        2000 non-null   float64
 10  Amount_Paid     2000 non-null   float64
 11  Payment_Status  2000 non-null   object
 12  Student_Status  2000 non-null   object
 13  Year            2000 non-null   int32
 14  Quarter         2000 non-null   int32
 15  Month_Name      2000 non-null   object
 16  Week            2000 non-null   UInt32
 17  Day             2000 non-null   object
dtypes: UInt32(1), datetime64[ns](1), float64(2), int32(2), int64(1), object(11)
memory usage: 275.4+ KB

In [ ]:
df.isnull().sum()

Payment_ID        0
Payment_Date      0
Month             0
Student_ID        0
Subject           0
Level             0
Tutor             0
Payment_Method    0
Course_Fee        0
Discount          0
Amount_Paid       0
Payment_Status    0
Student_Status    0
Year              0
Quarter           0
Month_Name        0
Week              0
Day               0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv("Harvard_English_Data_Clean.csv",index=False)

In [ ]:
from google.colab import files
files.download("Harvard_English_Data_Clean.csv")